name: 'build docker'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push for releases
        id: docker_build
        uses: docker/build-push-action@v2
        if: ${{ success() && github.event_name == 'push' }}
        with:
          context: .
          platforms: linux/arm/v7,linux/amrm64/v8
          push: true
          tags: mrdavidkovacs/anniversariesapi:latest

      - name: Build and push for pullrequests
        id: docker_build
        uses: docker/build-push-action@v2
        if: ${{ success() && github.event_name == 'push' }}
        with:
          context: .
          platforms: linux/arm/v7,linux/amrm64/v8
          push: true
          tags: mrdavidkovacs/anniversariesapi:PR-$PR