name: 'build docker'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push for releases
        id: docker_build_latest
        uses: docker/build-push-action@v2
        if: ${{ success() && github.event_name == 'push' }}
        with:
          context: .
          platforms: linux/arm/v7,linux/amrm64/v8
          push: true
          tags: mrdavidkovacs/anniversariesapi:latest

      - name: Build and push for pullrequests
        id: docker_build_pr
        uses: docker/build-push-action@v2
        if: ${{ success() && github.event_name == 'push' }}
        with:
          context: .
          platforms: linux/arm/v7,linux/amrm64/v8
          push: true
          tags: mrdavidkovacs/anniversariesapi:PR-${{ github.event.number }}