name: 'build docker'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Sets env vars for production
        run: |
          echo "DOCKER_IMAGE_NAME=mrdavidkovacs/anniversariesapi:latest" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: Sets env vars for pullrequests
        run: |
          echo "DOCKER_IMAGE_NAME=mrdavidkovacs/anniversariesapi:PR-${{ github.event.number }}" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64, linux/arm64 #, linux/arm/v7
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}