name: 'build docker'

on:
  push:
    branches:
    - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "mrdavidkovacs"
          password: ${{ secrets.ACCESS_TOKEN }}
          repository: mrdavidkovacs/anniversariesapi
          platforms: linux/arm/v7,linux/amrm64/v8
          push: true
          tags: latest