name: npm audit fix

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  npm-audit-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: (cd Anniversaries.Web && npm ci) 
      - uses: oke-py/npm-audit-action@v1.8.4
        with:
          audit_level: moderate
          #issue_assignees: oke-py
          #issue_labels: vulnerability,test
          dedupe_issues: true
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          working_directory: Anniversaries.Web
